name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      env:
        CR_PAT: ${{ secrets.PAT }}
      run: |
        echo $CR_PAT | docker login ghcr.io -u AWinterman --password-stdin
        docker build . --file Dockerfile --tag ghcr.io/wintersparkle/workstation:$(date +%s) --tag ghcr.io/wintersparkle/workstation:latest
        docker push ghcr.io/wintersparkle/workstation
